// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdyfKt-WuaGWQAG2WuKgoXYhdziDvHXOQ',
    appId: '1:805807504729:web:e029b4d00a27f31b226048',
    messagingSenderId: '805807504729',
    projectId: 'fir-project-b355e',
    authDomain: 'fir-project-b355e.firebaseapp.com',
    storageBucket: 'fir-project-b355e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5IUuYseMu-Ss88uwh_UwNeLfgZvG_Ae4',
    appId: '1:805807504729:android:5a37a4e6c9bad564226048',
    messagingSenderId: '805807504729',
    projectId: 'fir-project-b355e',
    storageBucket: 'fir-project-b355e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdGpdiEpg23K2YYJac7VJ2h1JgElRUkCM',
    appId: '1:805807504729:ios:9e924176bf287fd7226048',
    messagingSenderId: '805807504729',
    projectId: 'fir-project-b355e',
    storageBucket: 'fir-project-b355e.appspot.com',
    iosBundleId: 'com.example.instaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdGpdiEpg23K2YYJac7VJ2h1JgElRUkCM',
    appId: '1:805807504729:ios:6a94c3483503ad64226048',
    messagingSenderId: '805807504729',
    projectId: 'fir-project-b355e',
    storageBucket: 'fir-project-b355e.appspot.com',
    iosBundleId: 'com.example.instaapp.RunnerTests',
  );
}
